version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./download:/app/download  # Persistência dos arquivos baixados
    environment:
      - PYTHONUNBUFFERED=1
