version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./download:/app/download  # Persistência dos arquivos baixados
    environment:
      - PYTHONUNBUFFERED=1
      - DOWNLOAD_DIR=/app/download  # Define o diretório de download no container
    restart: always  # Garante que o container reinicie automaticamente em caso de falha
