name: Testar conexão SSH

on:
  workflow_dispatch: # Permite rodar manualmente

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HETZNER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HETZNER_HOST }} >> ~/.ssh/known_hosts

      - name: Testar conexão SSH
        run: |
          ssh ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} "echo Conexão SSH bem-sucedida!"
