name: Deploy para Hetzner

on:
  push:
    branches:
      - main  # Roda o deploy quando há push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v4

      - name: 🔑 Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "$HETZNER_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HETZNER_HOST >> ~/.ssh/known_hosts
        env:
          HETZNER_SSH_KEY: ${{ secrets.HETZNER_SSH_KEY }}

      - name: 🔌 Testar conexão SSH
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} "echo '✅ Conexão SSH bem-sucedida!'"

      - name: 🚀 Fazer deploy no Hetzner
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_HOST }} << 'EOF'
          cd /equatorial-web-scrapping  
          git pull origin main 
          docker-compose down  
          docker-compose up -d --build  
            echo '🚀 Deploy finalizado com sucesso!'
          EOF
